export const INIT_LOCATION = "INIT_LOCATION";
export const ADD_LOCATION = "ADD_LOCATION";
export const FETCH_ALL_LOCATIONS = "FETCH_ALL_LOCATIONS";
export const GET_LOCATION = "GET_LOCATION";
export const SORT_DISTANCE = "SORT_DISTANCE";
export const TRAVEL_MODE = "TRAVEL_MODE";
